<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>JobTracker.BuildingBlocks.Infrastructure</RootNamespace>
    <AssemblyName>JobTracker.BuildingBlocks.Infrastructure</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Application\JobTracker.BuildingBlocks.Application.csproj" />
    <ProjectReference Include="..\SharedKernel\JobTracker.SharedKernel.csproj" />
  </ItemGroup>
</Project>
