<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="NetArchTest.Rules" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\BuildingBlocks\SharedKernel\JobTracker.SharedKernel.csproj" />
    <ProjectReference Include="..\..\src\BuildingBlocks\Application\JobTracker.BuildingBlocks.Application.csproj" />
    <ProjectReference Include="..\..\src\BuildingBlocks\Infrastructure\JobTracker.BuildingBlocks.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\BuildingBlocks\Presentation\JobTracker.BuildingBlocks.Presentation.csproj" />
    <ProjectReference Include="..\..\src\Modules\Jobs\Jobs.Domain\Jobs.Domain.csproj" />
    <ProjectReference Include="..\..\src\Modules\Jobs\Jobs.Application\Jobs.Application.csproj" />
    <ProjectReference Include="..\..\src\Modules\Jobs\Jobs.Infrastructure\Jobs.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\Modules\Jobs\Jobs.Presentation\Jobs.Presentation.csproj" />
    <ProjectReference Include="..\..\src\Modules\Jobs\Jobs.IntegrationEvents\Jobs.IntegrationEvents.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Using Include="Xunit" />
    <Using Include="FluentAssertions" />
  </ItemGroup>
</Project>
